// app/layout.tsx
import type { Metadata } from "next";
import { Oxygen } from "next/font/google";
import "./globals.css";

// Importez next/dynamic
import dynamic from 'next/dynamic';

const oxygen = Oxygen({
  variable: "--font-oxygen",
  subsets: ["latin"],
  weight: ["300", "400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Importation dynamique du composant "Providers"
const Providers = dynamic(() => import('./providers').then(mod => mod.Providers), { ssr: false });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${oxygen.className} antialiased`}>
        {/* Le composant "Providers" gère toute la logique client */}
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}