// app/dashboard/layout.tsx
import dynamic from 'next/dynamic';
import type { Metadata } from "next";
import "../globals.css";

const DashboardClient = dynamic(() => import('./components/dashboard'), { ssr: false });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <div  className="flex justify-center gap-2"> 
       <DashboardClient />
      <main className="w-[95%]">
        {children}
      </main>
  </div>
}